version: '3'

services: 
    nginx:
        build: 
            context: .
            dockerfile: Dockerfile-nginx
        volumes: 
            - ./:/var/www/symfony-source/
        ports: 
            - 8003:80
        networks: 
            - symfony
    php:
        build: 
            context: .
            dockerfile: Dockerfile-php
        environment: 
            APP_ENV: dev
            DATABASE_URL: mysql://symfony_user:symfony_password@mysql:3306/symfony_db?serverVersion=5.7
        expose: 
            - 8003
        volumes: 
            - ./:/var/www/symfony-source/
        networks: 
            - symfony
        depends_on: 
            - mysql
    mysql:
        image: mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment: 
            MYSQL_DATABASE: symfony_db
            MYSQL_USER: symfony_user
            MYSQL_PASSWORD: symfony_password
            MYSQL_ROOT_PASSWORD: root 
        ports: 
            - 3306:3306
        volumes: 
            - ./mysql:/var/lib/mysql
        networks: 
            - symfony  
networks: 
    symfony: